name: Build/Push Client

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image (server)
        uses: docker/build-push-action@v2
        with:
          context: ./npc
          file: ./npc/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/torpedodge-bot:${{ github.sha }}, ghcr.io/${{ github.repository_owner }}/torpedodge-bot:latest
